all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 10.0.1.230 # Replace with actual private IP from Terraform output
        web2:
          ansible_host: 10.0.1.78 # Replace with actual private IP from Terraform output
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/ansible-demo # Optional if using SSH keys
